version: '3'

services:
  redis:
    image: "redislabs/redismod:latest"
    ports:
      - "6379:6379"
  stream-current:
    image: "maguec/stream-current:latest"
    links:
      - "redis:redis"
    environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
